[package]
name = "eskaks"
version = "1.1.0"
edition = "2021"

[dependencies]

needletail = "0.6"

env_logger = "0.9"
rayon = "1.5"
crossbeam = "0.8"
indicatif = { version = "0.16", features = ["rayon"] }
log = "0.4"
rustc-hash = "1.1.0" 
clap = { version = "4.5.4", features = ["derive"] }

[profile.release]
opt-level      = 3
lto            = "fat"
codegen-units  = 1
panic          = "abort"
strip          = true
