[package]
name = "eskaks"
version = "0.1.0"
edition = "2021"

[dependencies]

needletail = "0.6"

env_logger = "0.9"
rayon = "1.5"
crossbeam = "0.8"
indicatif = { version = "0.16", features = ["rayon"] }
log = "0.4"
rustc-hash = "1.1.0" 
clap = { version = "4.5.4", features = ["derive"] }
crossbeam-channel = "0.5"

[profile.release]
opt-level      = 3          
lto            = "thin"     # o "fat" si quieres el último pun-to de rendimiento
codegen-units  = 1          # un solo CU mejora inlining (compila algo más lento)
panic          = "abort"    # opcional: binario más pequeño/rápido
